### ISSUE TITLE
Running BareMetal-kernel in qemu

### ISSUE THREAD

**Issue by ogoudron** [ReturnInfinity/BareMetal-kernel#11]
I would like to test BareMetal-kernel.
I have compiled kernel.sys with build_x86-64.sh script.
In src/X86-64 readme i can see that we use boot.bin file with qemu but i don't understand how to create boot.bin from kernel.sys.
Can you explain more in depth how to compile and run BareMetal-kernel with qemu ?

**Comment by ohnx** [comment]
Take a look at [this repository](https://github.com/ReturnInfinity/BareMetal), namely this files:

https://github.com/ReturnInfinity/BareMetal/blob/master/install.sh

(replace bmfs.image with boot.bin)

**Comment by ogoudron** [comment]
I have compiled pure64.sys and kernel.sys then i have done the following steps.
cat pure64.sys kernel.sys > software.sys
dd if=software.sys of=boot.bin bs=512 seek=16 conv=notrunc
qemu-system-x86_64 -machine q35 -cpu core2duo -smp 2 -m 1024 -kernel ./boot.bin

And the result is a qemu fatal error.
qemu: fatal: Trying to execute code outside RAM or ROM at 0x00000000000a0000

Tested on Ubuntu 14.04.

**Comment by IanSeyler** [comment]
Sorry, this isn't working just yet! I need to make some modifications to Pure64 for this to work correctly.

**Comment by ohnx** [comment]
Is it this version that doesn't work right now? I have a version of pure64
and BareMetal-kernel working fine on my pc...

**Comment by IanSeyler** [comment]
No, this is in regards to the multiboot startup within QEMU. I need to remove the 16-bit code from Pure64 as multiboot starts in 32-bit mode.

**Comment by ogoudron** [comment]
Could you update this issue when it will be time to test again ?
Thanks in advance.

**Comment by IanSeyler** [comment]
I'll post an initial update this evening. Pure64 is working via Multiboot but the BareMetal kernel currently hangs. I need to use GDB to debug it further but will still upload my current progress.

**Comment by IanSeyler** [comment]
The updated code is up now. Fixed the kernel hanging issue but it crashes later on due to (I think) there being no memory map for setting up the stack.

Keeping this issue open until it all works properly.

**Comment by IanSeyler** [comment]
Please be sure to check out https://github.com/ReturnInfinity/BareMetal-kernel/blob/master/src/x86-64/README.md for the execution/debugging instructions.

I'll fix the stack issue shortly.

**Comment by IanSeyler** [comment]
Will upload the crash fix this evening. New bug: The RTC doesn't seem to be firing.
