### ISSUE TITLE
newlib

### ISSUE THREAD

**Issue by ohnx** [ReturnInfinity/BareMetal-kernel#15]
I noticed that newlib is currently listed as something that BareMetal-kernel works with.

Does it really?

**Comment by IanSeyler** [comment]
Yes, I need to add the scripts/diffs still.

**Comment by ohnx** [comment]
I also have a version of `libBareMetal` [here](https://github.com/ohnx-osdev/BareMetal-kernel).

**Comment by IanSeyler** [comment]
Sweet! I'll add it into an api folder.
