### ISSUE TITLE
Port minIP to BareMetal

### ISSUE THREAD

**Issue by IanSeyler** [ReturnInfinity/BareMetal-kernel#16]
minIP is here: https://github.com/IanSeyler/minIP

It's a small C app with a very basic IP stack and web server.

**Comment by ohnx** [comment]
[KolibriOS](https://github.com/ohnx-osdev/KolibriOS-kernel) (up-to-date source can be found [here](http://websvn.kolibrios.org/listing.php?repname=Kolibri+OS&path=%2Fkernel%2Ftrunk%2F) has an IP stack already. While porting, maybe you could take a look at that too?

**Comment by IanSeyler** [comment]
Can take a look at it, sure. I'm pretty sure I've been in contact with hidnplayr before.

**Comment by ohnx** [comment]
There are other TCP implementations in C as well, such as:
https://github.com/ntruchsess/arduino_uip
and
https://github.com/tass-belgium/picotcp

**Comment by IanSeyler** [comment]
This was completed with the latest push: https://github.com/IanSeyler/minIP/commit/666c1340ab88783dc8865d360fb928d13f6696a9
