### ISSUE TITLE
C library

### ISSUE THREAD

**Issue by bumblebritches57** [ReturnInfinity/BareMetal-kernel#26]
Newlib is released under a variety of licenses, have you thought about using the Public Domain C library ([pdclib](https://bitbucket.org/pdclib/pdclib)) as your standard library?

**Comment by IanSeyler** [comment]
I'm open to any replacement C library. I originally picked Newlib due to the ease of writing the glue between the OS and library.

**Comment by tay10r** [comment]
How about [BareMetal-libc](https://github.com/ReturnInfinity/BareMetal-libc). It's under the same license as the rest of the project. We can just add the functionality as we need it. I already added some of the functions that were being used by Alloy.

**Comment by IanSeyler** [comment]
@tay10r That works for me! I like the idea of having our own as well as any bigger ones that support the OS (like newlib).
