### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by ohnx** [ReturnInfinity/BareMetal-kernel#4]
What happened to video mode in the kernel?

Why did it [get removed](https://www.diffchecker.com/w2ib63fu)?

**Comment by IanSeyler** [comment]
This repo can be thought of as a basic kernel. BareMetal OS will use this kernel along with patches to make use of graphics mode.

**Comment by ohnx** [comment]
Ah, okay. Are there any other differences between the two?
I'm trying to combine the two versions right now.

**Comment by IanSeyler** [comment]
Yes, this has no interface (CLI).

**Comment by ohnx** [comment]
Ah, okay.
Isn't that sort of fixing [ReturnInfinity/BareMetal-OS #40](https://github.com/ReturnInfinity/BareMetal-OS/issues/40)?

**Comment by ohnx** [comment]
I've tried to combine them [here](https://github.com/ohnx/a), but it appears as if there are some issues with the command line and it doesn't actually run on boot...

**Comment by IanSeyler** [comment]
Also, there is no file system in this kernel. Odd that you didn't get the
prompt though.

On Tue, Jul 7, 2015 at 4:55 PM, Mason X <notifications@github.com> wrote:

> I've tried to combine them here <https://github.com/ohnx/a>, but it
> appears as if there are some issues with the command line and it doesn't
> actually run on boot...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReturnInfinity/BareMetal-kernel/issues/4#issuecomment-119336521>
> .
>



-- 
Ian Seyler | Founder / Lead Programmer | Return Infinity |
ian.seyler@returninfinity.com | visit us at www.returninfinity.com

**Comment by ohnx** [comment]
Yeah, I realized what was wrong later.
I mis-copied some parts of the portion of the kernel that launches the CLI.

**Comment by ohnx** [comment]
... and I broke something.

**Comment by ohnx** [comment]
It appears as if the CLI needs to be aligned to 16.
Without these lines:
```
align 16
db 'DEBUG: CLI '
align 16
```
it simply doesn't work.
