### ISSUE TITLE
Enhanced dumping of memory

### ISSUE THREAD

**Issue by IanSeyler** [ReturnInfinity/BareMetal-kernel#45]
Should export in the format:

Memory address (rounded down), Hex values
`0x0123456789ABCDEF: 00 01 02 03 04 05 06 07  08 09 0A 0B 0C 0D 0E 0F`

Double space between 07 and 08 to separate (hopefully) aligned 64-bit values.

**Comment by tay10r** [comment]
Oh, I like this! The xxd utility can also convert this format back to binary. Might be worth looking up!

**Comment by IanSeyler** [comment]
Ideally it should only output the bytes that were requested.

For instance if you want 4 bytes at address 0x000000000010000E:

`0x0000000000100000: .. .. .. .. .. .. .. .. .. .. .. .. .. .. DE AD
0x0000000000100010: C0 DE .. .. .. .. .. .. .. .. .. .. .. .. .. ..`

**Comment by tay10r** [comment]
The later example looks pretty useful, because the data starts at the beginning of the line

**Comment by IanSeyler** [comment]
I'll skip the extra newline/spaces. Keeps the code short and sweet.

**Comment by tay10r** [comment]
I would advocate for keeping the newline. Printing it straight to the terminal might look messy otherwise.

**Comment by IanSeyler** [comment]
After 16 bytes, sure.

**Comment by tay10r** [comment]
Oh! Okay no worries, you can get rid of it
