### ISSUE TITLE
documentation & code discrepancies

### ISSUE THREAD

**Issue by ohnx** [ReturnInfinity/BareMetal-kernel#6]
The documentation says that system functions are `b_`something and some even show examples for that, but in actual code it's `os_`.

**Comment by IanSeyler** [comment]
Calls within the kernel use `os_`. Apps use `b_`.

The `b_` names are just aliased to the kernel call table: https://github.com/ReturnInfinity/BareMetal-kernel/blob/master/src/x86-64/kernel.asm#L20

**Comment by ohnx** [comment]
yes, but in some of the assembly examples, `b_` is used.

**Comment by IanSeyler** [comment]
Where? In this repo?

**Comment by ohnx** [comment]
yep. I can fix it though.
